GEOPY-467
MiraGeoscience/geoapps pull request #293
Opened 2022-03-09 16:51 UTC by domfournier

2022-03-16 20:44 UTC, benk-mira requested changes
A couple of little details in there, but most importantly, I think we're missing something writing the default files.  I'll move on to testing to look into it further.

2022-03-16 21:54 UTC, domfournier commented on geoapps/create/octree_mesh.py
> +            validation_options={"disabled": True},
It will be validated on Line 230 when creating `OctreeParams`, and again on the `write_input_file`

2022-03-16 22:03 UTC, domfournier commented on geoapps/drivers/components/data.py
> +        self.locations = super().get_locations(self.entity)
Correct. Seems cleaner that way. The `params._uuid_promoter` handles it.

2022-03-16 22:09 UTC, domfournier commented on geoapps/io/Inversion/params.py
> -    def write_input_file(
I will challenge that we never need none_map. But regardless, `input_file.write_ui_json` still handles it. So technically we could store those none_maps on the params (default `none_maps = None`) and always send it with the base_params

2022-03-16 22:09 UTC, domfournier commented on geoapps/io/Inversion/params.py
> -    def write_input_file(
I will challenge that we never need none_map. But regardless, `input_file.write_ui_json` still handles it. So technically we could store those none_maps on the params (default `none_maps = None`) and always send it with the base_params

2022-03-17 18:36 UTC, benk-mira commented on geoapps/create/octree_mesh.py
> +            validation_options={"disabled": True},
gotcha

2022-03-17 18:37 UTC, domfournier commented on geoapps/base.py
> +                            except (ValueError, AttributeError, TypeError):
Yea just going through the apps right now, and doesn't look like we need the try at all anymore. The utils are doing the work.

2022-03-17 18:38 UTC, domfournier commented on geoapps/base.py
> +                            except (ValueError, AttributeError, TypeError):
I ll remove until we find a case for it in testing

2022-03-17 18:39 UTC, domfournier commented on geoapps/base.py
> +        time.sleep(1)
Fair enough. Changing to while loop

2022-03-17 18:44 UTC, domfournier commented on geoapps/base.py
> +        time.sleep(1)
Actually I don't think so. If GA isn't monitoring, then nothing will ever happen... according to Kris, the system triggers ga, so 1 sec is plenty...

2022-03-17 20:01 UTC, domfournier commented on geoapps/inversion/dcip_inversion_app.py
>              try:
Fair enough. Changed to better logical

2022-03-17 20:02 UTC, domfournier commented on geoapps/io/Inversion/params.py
> -    def write_input_file(
Pushed a change on GEOPY-472

2022-03-17 20:04 UTC, domfournier commented on geoapps/io/validation.py
> +        # TODO This check should be handled by a group validator
This file can go enterely. Deleting now.

2022-03-17 20:07 UTC, domfournier commented on geoapps/io/write_default_uijson.py
> +        params.write_input_file(name=filename, path=path, validate=False)
Should be fixed by latest GEOPY-472

2022-03-17 20:08 UTC, domfournier commented on tests/params_test.py
> -    ifile = InputFile()
I think that's handled by geoh5py at this point.

2022-03-17 21:45 UTC, benk-mira approved these changes
Great!

2022-03-18 17:06 UTC, benk-mira approved these changes

2022-03-18 17:07 UTC, merged