Geopy 500
MiraGeoscience/geoapps pull request #329
Opened 2022-05-09 18:14 UTC by benk-mira

Addition of an environment-GA.yml and install_ga.bat files that define a minimal install of geoapps for inversion.  Includes restructing of utils and imports in geoapps.  See also PRs of geoana, simpeg for accompanying changes

2022-05-10 15:28 UTC, sebhmg requested changes
I am not pretending to review all the changes here ! 😉 

please see some suggestions and question.

Also `pip_requirements.txt` is empty and seems unused.

2022-05-12 17:52 UTC, benk-mira commented on geoapps/utils/importing.py
> +    )
Done

2022-05-12 17:58 UTC, benk-mira commented on geoapps/utils/io.py
> +    return [float(val) for val in string.split(",") if len(val) > 0]
done

2022-05-12 18:54 UTC, benk-mira commented on geoapps/utils/general.py
> +#  Copyright (c) 2022 Mira Geoscience Ltd.
Done

2022-05-12 18:54 UTC, benk-mira commented on geoapps/utils/io.py
> +    return [float(val) for val in string.split(",") if len(val) > 0]
actually - moved to new utils.string as per above comment

2022-05-16 17:17 UTC, benk-mira commented on tests/utils_test.py
> -def blockmodel_tensormesh_equivalency(ws, origin, x, y, z, ignore_origin=False):
yes it's gone.  I found a handful of utilities that were not being used in the code.  @domfournier will go through these during the code review and rescue anything really useful.

2022-05-16 21:36 UTC, sebhmg requested changes
one last minor thing about the style for docstring

please see comments

2022-05-16 21:36 UTC, sebhmg commented on geoapps/utils/plotting.py
> +    """
**suggestion:** use a consistent  doc style (e.g. `sorted_alphanumeric_list()`)

2022-05-16 21:36 UTC, sebhmg commented on geoapps/utils/statistics.py
> +    """
**suggestion:** use a consistent doc style (e.g. sorted_alphanumeric_list())

2022-05-18 16:34 UTC, benk-mira commented on geoapps/utils/plotting.py
> +    """
done

2022-05-18 16:35 UTC, benk-mira commented on geoapps/utils/statistics.py
> +    """
done

2022-05-18 20:34 UTC, sebhmg commented on geoapps/utils/statistics.py
> +    :param size: Number of indices (rows) to be extracted from the original array
preserve type in docstring, or, better, have it as type hint on the signature
```
def random_sampling(
    values: npt.NDArray[np.float64], size: int, method="histogram", n_bins=100, bandwidth=0.2, rtol=1e-4
) -> npt.NDArray[np.int_]:
```

See typing annotations for numpy: https://numpy.org/devdocs/reference/typing.html#api

2022-05-18 20:38 UTC, sebhmg commented on geoapps/utils/plotting.py
> +    :param input_string: Input string value of type `val1:val2:ii` and/or
can have typing in signature if not in doc anymore
```
def input_string_2_float(input_string: str) -> npt.NDArray[np.int_] :
```

See typing annotations for numpy: https://numpy.org/devdocs/reference/typing.html#api

2022-05-18 20:41 UTC, sebhmg reviewed
non-blocking comments about preserving the type information:
- either in comment, as `:param param_type param_name: parameter description` (some example on [PyCharm doc](https://www.jetbrains.com/help/pycharm/using-docstrings-to-specify-types.html#:~:text=%3Aparam%20param_type%20param_name%3A))
- or using  typing in signature

2022-05-18 21:10 UTC, sebhmg approved these changes

2022-05-18 21:33 UTC, sebhmg approved these changes

2022-05-19 02:10 UTC, sebhmg approved these changes

2022-05-19 16:09 UTC, benk-mira commented on tests/utils_test.py
> +# def test_blockmodel_nonuniqueness(tmp_path):
removed

2022-05-19 19:54 UTC, sebhmg submitted a review, later dismissed

2022-05-26 20:28 UTC, sebhmg commented
see continuation in https://github.com/MiraGeoscience/geoapps/pull/341

2022-05-26 20:28 UTC, closed without merging