GEOPY-571: Merge shared_utils.utils.rotate_xy with utils.models.rotate_xyz
MiraGeoscience/geoapps pull request #370
Opened 2022-06-30 20:18 UTC by jamiefb

2022-07-04 15:23 UTC, benk-mira requested changes
Great - thanks for this!  Let's just add to the docstrings what direction the rotations are for.

2022-07-04 15:23 UTC, benk-mira commented on geoapps/shared_utils/utils.py
> +    :param theta: Angle of rotation around z-axis in degrees.
Should state the direction here.  Are they still counterclockwise?

2022-07-04 16:29 UTC, benk-mira submitted a review, later dismissed
That should do it!

2022-07-04 16:29 UTC, benk-mira commented on geoapps/shared_utils/utils.py
> +    Perform a counterclockwise rotation of scatter points around the z-axis, then x-axis, about a center point.
Perfect, thanks

2022-07-05 22:18 UTC, domfournier approved these changes

2022-07-05 22:18 UTC, merged