GEOPY-614
MiraGeoscience/geoapps pull request #403
Opened 2022-09-07 21:29 UTC by benk-mira

2022-09-14 22:04 UTC, domfournier requested changes
I think we should revise the also as it will be pretty slow and prone to fail if you have overlapping lines. We can talk about it.

2022-09-15 16:03 UTC, benk-mira commented on geoapps/utils/surveys.py
> +            tops.append(locations[:, 2][np.where(inds == i)[0]].max())
I generalized the function to handle 2D sections so I could re-use elsewhere

2022-09-15 16:04 UTC, benk-mira commented on geoapps/utils/surveys.py
> +def new_neighbors(distances, neighbors, nodes):
done

2022-09-15 16:04 UTC, benk-mira commented on geoapps/utils/surveys.py
> +    """index into neighbor arrays excluding zero distance and past neighbors."""
done

2022-09-15 16:05 UTC, benk-mira commented on geoapps/utils/surveys.py
> +    """index into neighbor arrays excluding zero distance and past neighbors."""
Done, sorry

2022-09-15 16:40 UTC, benk-mira commented on geoapps/utils/surveys.py
> +        np.sqrt(((locs[:, 0] - start_loc[0]) ** 2) + ((locs[:, 1]) - start_loc[1]) ** 2)
Indeed, I forgot about the axis option.  Thanks!

2022-09-15 17:06 UTC, benk-mira commented on geoapps/utils/surveys.py
> +
done

2022-09-15 19:56 UTC, domfournier commented on geoapps/utils/surveys.py
> +    distances, neighbors = tree.query(point, n)
Correct. New issue to work on this later GEOPY-638

2022-09-15 22:08 UTC, domfournier approved these changes
Grand

2022-09-15 22:09 UTC, domfournier approved these changes

2022-09-15 22:09 UTC, merged