GEOPY-689
MiraGeoscience/geoapps pull request #445
Opened 2022-11-16 18:56 UTC by benk-mira

2022-11-21 19:33 UTC, domfournier requested changes
Would be so nice to have to the base inversion constants to handle the core ui part... anyway. Looking good overall. Few edits and we should be good.

2022-11-21 19:33 UTC, domfournier commented on geoapps/inversion/electricals/direct_current/two_dimensions/constants.py
> +    "receivers_offset_y": {
Thought we got rid of those?

2022-11-21 19:33 UTC, domfournier commented on geoapps/inversion/electricals/induced_polarization/three_dimensions/constants.py
> +    "title": "SimPEG Induced Polarization 3d inversion",
```suggestion
    "title": "SimPEG Induced Polarization 3D inversion",
```

2022-11-21 19:33 UTC, domfournier commented on geoapps/inversion/electricals/induced_polarization/three_dimensions/constants.py
> +        "association": ["Cell", "Vertex"],
```suggestion
        "association": "Cell",
```

2022-11-21 19:33 UTC, domfournier commented on geoapps/inversion/electricals/direct_current/three_dimensions/constants.py
> +        "association": ["Cell", "Vertex"],
```suggestion
        "association": "Cell",
```

2022-11-21 19:33 UTC, domfournier commented on geoapps/inversion/electricals/induced_polarization/three_dimensions/constants.py
> +    "receivers_offset_y": {
Same here remove offset_x and offset_y

2022-11-21 19:33 UTC, domfournier commented on geoapps/inversion/electricals/induced_polarization/two_dimensions/constants.py
> +    "title": "Induced Polarization (IP) 2D forward",
```suggestion
    "title": "Induced Polarization (IP) 2D Forward",
```

2022-11-21 19:33 UTC, domfournier commented on geoapps/inversion/electricals/induced_polarization/two_dimensions/constants.py
> +    "receivers_offset_y": {
Same here - remove horizontal offsets

2022-11-21 19:33 UTC, domfournier commented on geoapps/inversion/potential_fields/gravity/constants.py
> +    "title": "Gravity forward",
Can you double-check all the titles? Not sure we are consistant.

2022-11-21 19:33 UTC, domfournier commented on geoapps/inversion/potential_fields/gravity/constants.py
> +        "association": ["Cell", "Vertex"],
```suggestion
        "association": "Cell",
```

2022-11-21 19:33 UTC, domfournier commented on geoapps/inversion/potential_fields/magnetic_scalar/constants.py
> +        "association": ["Cell", "Vertex"],
```suggestion
        "association": "Cell",
```

2022-11-21 19:33 UTC, domfournier commented on geoapps/inversion/potential_fields/magnetic_vector/constants.py
> +        "association": ["Cell", "Vertex"],
```suggestion
        "association": "Cell",
```

2022-11-21 22:31 UTC, benk-mira commented on geoapps/inversion/electricals/direct_current/two_dimensions/constants.py
> +    "receivers_offset_y": {
yep, I took a shortcut.  Removed now.

2022-11-21 22:34 UTC, benk-mira commented on geoapps/inversion/electricals/induced_polarization/three_dimensions/constants.py
> +    "title": "SimPEG Induced Polarization 3d inversion",
Done

2022-11-21 22:34 UTC, benk-mira commented on geoapps/inversion/electricals/induced_polarization/three_dimensions/constants.py
> +    "title": "SimPEG Induced Polarization 3d Forward",
Done

2022-11-21 22:36 UTC, benk-mira commented on geoapps/inversion/electricals/induced_polarization/two_dimensions/constants.py
> +    "receivers_offset_y": {
Done

2022-11-22 19:48 UTC, domfournier approved these changes
good to go

2022-11-22 19:48 UTC, domfournier commented
@benk-mira Merge?

2022-11-25 16:17 UTC, merged