GEOPY-787
MiraGeoscience/geoapps pull request #586
Opened 2023-07-13 17:17 UTC by domfournier

2023-07-13 20:59 UTC, benk-mira requested changes
mostly just cleanups.  Well done man!

2023-07-13 20:59 UTC, benk-mira commented on geoapps/inversion/joint/joint_cross_gradient/driver.py
> +        #
```suggestion
        
```

2023-07-13 20:59 UTC, benk-mira commented on geoapps/inversion/joint/joint_cross_gradient/driver.py
> +                        print(param, getattr(driver.params, param))
cleanup

2023-07-13 20:59 UTC, benk-mira commented on geoapps/inversion/joint/joint_cross_gradient/driver.py
> +            n_values = int(np.sum(self.models.active_cells))
```suggestion
            n_values = self.models.n_active
```

2023-07-13 20:59 UTC, benk-mira commented on geoapps/inversion/joint/joint_cross_gradient/driver.py
> +            n_values = int(np.sum(self.models.active_cells))
```suggestion
            n_values = self.models.n_active
```

2023-07-13 20:59 UTC, benk-mira commented on geoapps/inversion/joint/joint_cross_gradient/params.py
> +    Parameter class for gravity->density inversion.
```suggestion
    Parameter class for cross-gradient joint inversion.
```

2023-07-13 20:59 UTC, benk-mira commented on geoapps/inversion/joint/joint_cross_gradient/params.py
> +        #     raise ValueError(
cleanup

2023-07-13 20:59 UTC, benk-mira commented on geoapps/inversion/driver.py
> +    # file = str(Path(sys.argv[1]).resolve())
```suggestion
```

2023-07-14 14:53 UTC, domfournier commented on geoapps/inversion/driver.py
> +            self._n_values = int(np.sum(self.models.active_cells))
Cool yep. It is `n_active` right now in `models`, but that works.

2023-07-14 14:55 UTC, domfournier commented on geoapps/inversion/joint/joint_cross_gradient/driver.py
> +            n_values = int(np.sum(self.models.active_cells))
Same, yep.

2023-07-14 15:57 UTC, benk-mira commented on geoapps/inversion/driver.py
> +            self._n_values = int(np.sum(self.models.active_cells))
whoops, that's what i meant!

2023-07-14 18:28 UTC, benk-mira approved these changes
Love it!

2023-07-14 19:26 UTC, merged