GEOPY-1194: Prepare release
MiraGeoscience/geoapps pull request #631
Opened 2023-11-07 18:50 UTC by domfournier

2023-11-07 19:50 UTC, sebhmg requested changes
version to be formatted according to Semver specifications

2023-11-07 19:50 UTC, sebhmg commented on pyproject.toml
> +version = "0.11.0-rc1"
use format compliant with Semver
```suggestion
version = "0.11.0-rc.1"
```

2023-11-07 19:50 UTC, sebhmg commented on docs/conf.py
> +release = "0.11.0-rc1"
use consistently a format compliant with Semver
```suggestion
release = "0.11.0-rc.1"
```

2023-11-08 16:40 UTC, andrewg-mira submitted a review, later dismissed

2023-11-08 16:50 UTC, domfournier commented
@sebhmg Somehow it's still requesting for changes. Can you review when you have the chance?

2023-11-08 18:46 UTC, domfournier commented
Hang on one sec, need to update mira-simpeg version

2023-11-08 19:21 UTC, sebhmg submitted a review, later dismissed

2023-11-09 18:15 UTC, merged